name: Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: [0.0.9]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup seki
      uses: ./
      with:
        version: ${{ matrix.version }}

    - name: Capture gh version installed
      run: |
        export GH_VERSION=$( seki version )
        echo 'GH_VERSION_INSTALLED<<EOF' >> $GITHUB_ENV
        seki version >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Verify
      shell: python
      env:
        GH_VERSION_EXPECTED: ${{ matrix.version }}
      run: |
        import sys, os
        sys.exit(
            int(not os.environ["GH_VERSION_EXPECTED"] in os.environ["GH_VERSION_INSTALLED"])
        )
